version: '3.5'
services:
  web:
    build: ./src
    command: flask run --host 0.0.0.0
    env_file: database.conf
    ports:
      - 5000:5000
    depends_on: 
      - database
  database:
    container_name: postgres
    image: postgres
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: